### ISSUE TITLE
android_x86 support

### ISSUE THREAD

**Issue by liotcheg** [anteo/torrent2http#1]
Do you plan android_x86 platform support?

**Comment by liotcheg** [comment]
I think I should have posted it in https://github.com/anteo/script.module.torrent2http
As far as I understand, android_x86 is supported and only a precompiled binary is missing for KODI.
Any chance you can add it? 
Thank you!

**Comment by anteo** [comment]
Not possible for now. Go still lack of Android x86 build support.
