### ISSUE TITLE
Compile torrent2http with PIE support

### ISSUE THREAD

**Issue by Diblo** [anteo/torrent2http#3]
Hi @anteo 
Can you add the flag to compile torrent2http with PIE support? :)
- https://en.m.wikipedia.org/wiki/Position-independent_code
- http://stackoverflow.com/questions/24818902/running-a-native-library-on-android-l-error-only-position-independent-executab
- https://golang.org/src/cmd/go/build.go?h=pie

Greeting
Diblo

**Comment by anteo** [comment]
v1.0.5 supports PIE now
